import type { Customer } from "@/types/customer";

const DEMO_CUSTOMERS: Customer[] = [
  {
    id: "cust_001",
    name: "Aarav Mehta",
    email: "aarav.mehta@northstar.io",
    plan: "Enterprise",
    status: "Active",
    joinedDate: "12 Jan 2025",
    country: "India",
    totalSpend: 18450,
  },
  {
    id: "cust_002",
    name: "Sophia Bennett",
    email: "sophia.bennett@brightlabs.com",
    plan: "Pro",
    status: "Active",
    joinedDate: "28 Jan 2025",
    country: "United Kingdom",
    totalSpend: 6240,
  },
  {
    id: "cust_003",
    name: "Pratigya Sharma",
    email: "pratigya.sharma@orbitworks.in",
    plan: "Pro",
    status: "Active",
    joinedDate: "17 Mar 2025",
    country: "India",
    totalSpend: 7350,
  },
  {
    id: "cust_004",
    name: "Emma Rodriguez",
    email: "emma.rodriguez@cloudpeak.io",
    plan: "Enterprise",
    status: "Active",
    joinedDate: "19 Feb 2025",
    country: "Spain",
    totalSpend: 15380,
  },
  {
    id: "cust_005",
    name: "Liam Carter",
    email: "liam.carter@novatech.com",
    plan: "Free",
    status: "Active",
    joinedDate: "03 Mar 2025",
    country: "Canada",
    totalSpend: 980,
  },
  {
    id: "cust_006",
    name: "Daniel Kim",
    email: "daniel.kim@vertexlabs.co",
    plan: "Pro",
    status: "Active",
    joinedDate: "06 Feb 2025",
    country: "United States",
    totalSpend: 4820,
  },
  {
    id: "cust_007",
    name: "Oliver Wilson",
    email: "oliver.wilson@pixelgrid.co.uk",
    plan: "Free",
    status: "Inactive",
    joinedDate: "29 Mar 2025",
    country: "United Kingdom",
    totalSpend: 1260,
  },
  {
    id: "cust_008",
    name: "Mia Anderson",
    email: "mia.anderson@atlasdigital.com",
    plan: "Pro",
    status: "Active",
    joinedDate: "11 Apr 2025",
    country: "United States",
    totalSpend: 5480,
  },
  {
    id: "cust_009",
    name: "Arjun Kapoor",
    email: "arjun.kapoor@finbyte.in",
    plan: "Enterprise",
    status: "Active",
    joinedDate: "24 Apr 2025",
    country: "India",
    totalSpend: 21600,
  },
  {
    id: "cust_010",
    name: "Isabella Rossi",
    email: "isabella.rossi@studiovero.it",
    plan: "Pro",
    status: "Inactive",
    joinedDate: "08 May 2025",
    country: "Italy",
    totalSpend: 3920,
  },
  {
    id: "cust_011",
    name: "Noah Thompson",
    email: "noah.thompson@launchpad.io",
    plan: "Free",
    status: "Active",
    joinedDate: "21 May 2025",
    country: "Australia",
    totalSpend: 740,
  },
  {
    id: "cust_012",
    name: "Ananya Verma",
    email: "ananya.verma@marketflow.in",
    plan: "Pro",
    status: "Active",
    joinedDate: "04 Jun 2025",
    country: "India",
    totalSpend: 6810,
  },
  {
    id: "cust_013",
    name: "Ethan Brown",
    email: "ethan.brown@horizonlabs.com",
    plan: "Enterprise",
    status: "Active",
    joinedDate: "18 Jun 2025",
    country: "United States",
    totalSpend: 17250,
  },
  {
    id: "cust_014",
    name: "Charlotte Martin",
    email: "charlotte.martin@monarch.fr",
    plan: "Free",
    status: "Active",
    joinedDate: "02 Jul 2025",
    country: "France",
    totalSpend: 1180,
  },
  {
    id: "cust_015",
    name: "Kabir Malhotra",
    email: "kabir.malhotra@stackworks.in",
    plan: "Pro",
    status: "Active",
    joinedDate: "16 Jul 2025",
    country: "India",
    totalSpend: 5290,
  },
  {
    id: "cust_016",
    name: "Amelia Clark",
    email: "amelia.clark@northwind.co",
    plan: "Enterprise",
    status: "Active",
    joinedDate: "31 Jul 2025",
    country: "United States",
    totalSpend: 19480,
  },
  {
    id: "cust_017",
    name: "Lucas Moretti",
    email: "lucas.moretti@dataforge.io",
    plan: "Pro",
    status: "Inactive",
    joinedDate: "14 Aug 2025",
    country: "Brazil",
    totalSpend: 4170,
  },
  {
    id: "cust_018",
    name: "Ishita Patel",
    email: "ishita.patel@cloudnest.in",
    plan: "Free",
    status: "Active",
    joinedDate: "27 Aug 2025",
    country: "India",
    totalSpend: 890,
  },
  {
    id: "cust_019",
    name: "Henry Davis",
    email: "henry.davis@apexsystems.com",
    plan: "Enterprise",
    status: "Active",
    joinedDate: "09 Sep 2025",
    country: "United States",
    totalSpend: 16320,
  },
  {
    id: "cust_020",
    name: "Sophie Laurent",
    email: "sophie.laurent@atelierdata.fr",
    plan: "Pro",
    status: "Active",
    joinedDate: "22 Sep 2025",
    country: "France",
    totalSpend: 5740,
  },
  {
    id: "cust_021",
    name: "Rohan Gupta",
    email: "rohan.gupta@quantix.in",
    plan: "Enterprise",
    status: "Active",
    joinedDate: "07 Oct 2025",
    country: "India",
    totalSpend: 12890,
  },
  {
    id: "cust_022",
    name: "Grace Taylor",
    email: "grace.taylor@blueorbit.com",
    plan: "Free",
    status: "Inactive",
    joinedDate: "19 Oct 2025",
    country: "Canada",
    totalSpend: 620,
  },
  {
    id: "cust_023",
    name: "Benjamin Lee",
    email: "benjamin.lee@zenithlabs.com",
    plan: "Pro",
    status: "Active",
    joinedDate: "03 Nov 2025",
    country: "Singapore",
    totalSpend: 6480,
  },
  {
    id: "cust_024",
    name: "Neha Joshi",
    email: "neha.joshi@insightworks.in",
    plan: "Pro",
    status: "Active",
    joinedDate: "17 Nov 2025",
    country: "India",
    totalSpend: 4620,
  },
];

export const customerService = {
  async getCustomers(): Promise<Customer[]> {
    await new Promise((resolve) => setTimeout(resolve, 1000));

    return DEMO_CUSTOMERS;
  },
};